### PR TITLE
Allow response status of 0 for request stubs

### PR DESCRIPTION
**Pull request by kiramclean**
This fixes the issues described here: https://github.com/jasmine/jasmine-ajax/issues/141

As mentioned in that issue, `0` is a [valid status](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/status) for an ajax request or response (either while it is still in flight or if it errors for certain reasons, like a [network failure](https://fetch.spec.whatwg.org/#responses)).

I'm also interested in stubbing a response status of 0 in some tests and hoping you'll be open to reviewing this change. Thanks for all the work it takes to maintain a great library!

### CODE REVIEW

**Comment by slackersoft** [comment]
Thanks for taking a look at this. I'd like to see a couple of changes before we can merge this in.

* I don't see any tests for this functionality, which means it could get accidentally removed and no one would notice. See Jasmine's [contributing guide](https://github.com/jasmine/jasmine/blob/master/.github/CONTRIBUTING.md)
* We also want the combined `mock-ajax.js` file committed as part of the repository to enable jasmine-ajax to be used straight from github.

Please take a look at these, and I'll be happy to take another look. Thanks for using Jasmine!

**Comment by kiramclean** [comment]
Cool, thanks. I'll have a look. I just made this change with GitHub's fancy editing tool and noticed this didn't break any existing tests, so this particular behaviour is currently un-tested. Where would you like tests for this to be added and are there any special conventions you want new test coverage to follow?

I'm not sure when I'll get a chance to get the project set up locally to make those change -- hopefully sometime over the next couple of weekends. Thanks!

**Comment by slackersoft** [comment]
The `requestStub` has a set of unit tests, that seems like the best place for something like this.

**Comment by kiramclean** [comment]
@slackersoft The test is added and passes locally. Travis doesn't run properly.. I think because of permissions issues. All the build jobs except for the phantomjs one exit early with "skipping tests since we can't use sauce". The phantom JS one passes once then fails the second time. I tried to ssh into the build to try to see what's going on (following [these instructions](https://docs.travis-ci.com/user/running-build-in-debug-mode/) but get denied access:

```json
{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
}
```
Let me know if I can get access to debug, or if you can run the build the the right credentials.

**Comment by sgravrock** [comment]
You should be able to reproduce the test failures locally by doing a `bundle install` and then `JASMINE_BROWSER=phantomjs bash travis-script.sh`. Running a `grunt build` and then committing the changes to the generated `lib/mock-ajax.js` should be all it takes to get the tests passing.

**Comment by kiramclean** [comment]
Great, it worked. Thanks so much! This is ready for more review now.

**Comment by slackersoft** [comment]
Merged. Thanks for using Jasmine!

**Comment by kiramclean** [comment]
Cool! Thanks for accepting the changes. What's the release schedule like for this library? Is there any way to get updated when this makes it into a release we can use?

**Comment by slackersoft** [comment]
The release schedule is fairly sporadic for Jasmine-Ajax. We tend to get time to put everything together in bursts. I think many people also use the library simply by downloading the `mock-ajax.js` file out of [lib](https://github.com/jasmine/jasmine-ajax/tree/master/lib) and including it in their Jasmine helpers dir. 

We'll probably try to cut a new release soon(ish), possibly waiting for one or more of the other existing PRs to get completed, depending on their timing.

**Pull request closed without merging**
