### PR TITLE
fix progress event requires parameter

### PR DESCRIPTION
**Pull request by SunboX**

### CODE REVIEW

**Comment by slackersoft** [comment]
We are unable to accept this pull request at this time because:

* There are no specs. Jasmine is a testing framework, and any new feature should have tests.
* The build for your PR is red, because you've broken existing tests.

I am also not entirely sure what fix you are trying to address. Is there a browser/framework that passes this? Is it part of the XHR spec that I missed?

Please address these issues and either update this PR or create a new one. Thanks for using jasmine.

**Comment by SunboX** [comment]
I try to fix `jquery.soap.js` expecting a progress event parameter on this line:

https://github.com/doedje/jquery.soap/blob/master/jquery.soap.js#L282

**Comment by SunboX** [comment]
XHR Spec for the ProgressEvent Interface:

https://xhr.spec.whatwg.org/#interface-progressevent

**Comment by slackersoft** [comment]
Closing this in favor of #114.

**Pull request closed without merging**
